version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: agenda_kaki
      MYSQL_USER: user
      MYSQL_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
